#!/bin/bash

set -euo pipefail

if [ "$#" -eq 0 ]; then
    echo "No args"
    exit 1
fi

cmd="$1"; shift

DESTINATION="$(pwd)"

PROJECT="$(cd "$(dirname "$0")" && pwd)"



cd "$PROJECT"
poetry run python main.py "$cmd" "${@:1:$#-1}" "$DESTINATION"
